version: "2.2"
services:
  web:
    build: "./ruby"
    environment:
      PONG_DATABASE_PASSWORD: password
      TZ: Europe/Paris
    ports:
      - "80:80"
    volumes:
      - ./WebSite/Pong/:/Pong
    restart: always
	environment:
      PORT: '80'
  postgresql:
    build: "./PostGresSql"
    volumes:
      - ./PostGresSql/srcs/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Europe/Paris
  redis:
    build: "./redis"
    ports:
      - "6379:6379"
    restart: always
