version: "2.2"
services:
  web:
    build: "./ruby"
    ports:
      - "1080:1080"
    volumes:
      - /Users/hbaudet/Documents/Cursus42/Transcendance/WebSite/Pong:/Pong
    restart: always
  sql:
    build: "./PostGresSql"
    ports:
      - "5432:5432"
    restart: always
