version: "2.2"
services:
  web:
    build: "./ruby"
    ports:
      - "8080:80"
    volumes:
      - C:/Users/Nakusu/Desktop/42/Transcendance/WebSite/Pong/:/Pong
  sql:
    build: "./PostGresSql"
    ports:
      - "5432:5432"
