version: "2.2"
services:
  web:
    build: "./ruby"
    ports:
      - "80:80"
    volumes:
      - /Users/cyrillebertola/42/Transcendance/ruby/Pong/:/Pong
  sql:
    build: "./PostGresSql"
    ports:
      - "5432:5432"
