# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
  FT_UID: de7da913b73083565c31411bf025437eb9760ebb75951f12bffd9c8cfe230188
  FT_SECRET: 33e727ff803e2a8f233314c8774447c928bc2c3e4a248762e4ec2f9342809c61
  REDIS_DB: "0"
  REDIS_URL: redis://redis
  REDIS_PORT: "6379"
  FT_KEY: encryption_key_this_is_super_secure_trust_me_i_is_good_dev

